config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'admin', to: 'static_pages#admin'
  resources :entries
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/code_snippet.rb
class CodeSnippet < ApplicationRecord
  belongs_to :section
end

app/models/entry.rb
class Entry < ApplicationRecord
  has_many :sections, dependent: :destroy
  has_one_attached :image
  accepts_nested_attributes_for :sections, allow_destroy: true

  validates :title, presence: true
  validates :abstract, presence: true

  default_scope -> { order(created_at: :desc) }

  def display_image
    image.variant(resize_to_limit: [1200, 700])
  end

  def display_thumb_nail
    image.variant(resize_to_limit: [500, 500])
  end

  def self.recent_entries
    Entry.order('created_at desc').limit(10)
  end
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :entry
  has_one_attached :image
  has_one :code_snippet, dependent: :destroy
  accepts_nested_attributes_for :code_snippet, allow_destroy: true

  def display_image
    image.variant(resize_to_limit: [1200, 700])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  http_basic_authenticate_with name: ENV['HTTP_AUTH_NAME'],
                               password: ENV['HTTP_AUTH_PASSWORD'],
                               except: %i[index show]

  def new
    @entry = Entry.new
    @section = Section.new
    @entry.sections << @section
    @code_snippet = CodeSnippet.new
    @section.code_snippet = @code_snippet
  end

  def create
    @entry = Entry.new(entry_attributes)
    @entry.image.attach(params[:entry][:image])

    # attach each section image
    entry_attributes[:sections_attributes].to_h.each_with_index do |(_k, v), i|
      section = @entry.sections[i]
      section&.image&.attach(v[:image])
    end

    if @entry.save
      redirect_to @entry
    else
      render :new
    end
  end

  def show
    @entry = Entry.find(params[:id])
  end

  def index
    @entries = Entry.paginate(page: params[:page])
  end

  def edit
    @entry = Entry.find(params[:id])
  end

  def update
    @entry = Entry.find(params[:id])
    if @entry.update(entry_attributes)
      flash[:success] = 'Entry updated.'
      redirect_to @entry
    else
      render :edit
    end
  end

  def destroy
    Entry.find(params[:id]).destroy
    flash[:success] = 'Entry deleted.'
    redirect_to admin_path
  end

  private

  def entry_attributes
    params.require(:entry).permit(
      :title,
      :abstract,
      :image,
      sections_attributes: [:id, :content, :image, :_destroy, code_snippet_attributes: %i[code language]]
    )
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  http_basic_authenticate_with name: ENV['HTTP_AUTH_NAME'],
                               password: ENV['HTTP_AUTH_PASSWORD'],
                               except: :home

  def home
    @recent_entries = Entry.recent_entries
  end

  def admin
    @entries = Entry.paginate(page: params[:page])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + '_fields', f: builder)
    end
    link_to(name, '#', id: 'add-section-btn', data: { id: id, fields: fields.gsub("\n", '') })
  end

  def link_to_add_nested_fields(name, f, association, nested_association)
    new_object = f.object.send(association).klass.new
    new_nested_object = new_object.class.reflect_on_association(nested_association).klass.new
    new_object.send("#{nested_association}=", new_nested_object)
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + '_fields', f: builder)
    end
    link_to(name, '#', id: 'add-section-btn', data: { id: id, fields: fields.gsub("\n", '') })
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/code_snippets/_code_snippet.html.erb
<% unless code_snippet.code.nil? or code_snippet.code.blank? %> 
  <%= text_area code_snippet, :code,
    class: "codemirror", 
    data: { language: code_snippet.language ,
            code: code_snippet.code
          }
  %> 
<% end %> 

app/views/entries/_code_snippet_fields.html.erb
<div class="code-snippet-fields">
  <li>
    <%= f.label :language, class: "inline" %> 
    <%= f.select :language, options_for_select([
      "kotlin",
      "java",
      "groovy",
      "ruby",
      "html",
      "css",
      "scss",
      "javascript",
      "bash"
    ]), {}, class: "language-selector" %> 
  </li>
  <li>
    <%= f.label :code %> 
    <%= f.text_area :code, class: "code-field codemirror" %> 
  </li>
</div>

app/views/entries/_entry.html.erb
<div class="entry">
  <%= image_tag entry.display_thumb_nail, class: 'entry-image' if entry.image.attached? %> 
  <div class="entry-title">
    <%= entry.title %>
  </div>
  <div class="entry-date">
    <%= entry.created_at.strftime("%d-%m-%Y") %> 
  </div>
  <div class="entry-links">
    <%= link_to 'view entry', entry_path(entry) %> 
    <% if controller.controller_name == 'static_pages' && controller.action_name == 'admin' %> 
      <%= link_to 'delete entry',
                  entry, method: :delete,
                  class: 'delete-entry-btn',
                  data: { confirm: "Are you sure?" } 
      %> 

      <%= link_to 'edit entry', edit_entry_path(entry),class: 'edit-entry-btn' %> 
    <% end %> 
  </div>
  <div class="entry-abstract">
    <%= entry.abstract %>
  </div>

</div>

app/views/entries/_entry_form.html.erb
<%= form_with model: @entry, id: 'new-entry-form', local: true do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <ul>
    <li>
      <%= f.label :title %>
      <%= f.text_area :title, class: "title-field", placeholder: "Entry title.." %>
    </li>
    <li>
      <%= f.label :title_image, class: "inline" %> 
      <%= f.file_field :image, class: "inline" %> 
    </li>
    <li>
      <%= f.label :abstract %>
      <%= f.text_area :abstract, class: "abstract-field", placeholder: "Entry abstract.." %>
    </li>
    <div id="section-fields-container">
      <%= f.fields_for :sections do |f2| %>
        <%= render 'section_fields', f: f2 %>
      <% end %>
    </div>
    <li>
      <%= link_to_add_nested_fields 'Add new section', f, :sections, :code_snippet %>
    </li>
    <li>
      <%= f.submit 'Submit Entry', class: 'submit-btn' %>
    </li>
  </ul>
<% end %>

app/views/entries/_section_fields.html.erb
<div class="section-fields">
  <li>
    <%= f.label :content %>
    <%= f.text_area :content, class: "section-content-field", placeholder: "Section content.." %>
    <%= f.label :section_image, class: "inline" %> 
    <%= f.file_field :image %> 
  </li>
  <div class="code-snippet-container">
    <%= f.fields_for :code_snippet do |f2| %> 
      <%= render 'code_snippet_fields', f: f2 %> 
    <% end %> 
  </div>
  <li>
    <%= f.hidden_field :_destroy, class: 'section-destroy' %>
    <%=  link_to 'delete section', '#', class:'delete-section-btn' %>
  </li>
</div>

app/views/entries/edit.html.erb
<h1 class="page-title">Edit Entry</h1>
<div class="main-container">
  <%= render 'entry_form' %> 
</div>

app/views/entries/index.html.erb
<h1 class="page-title">Blog Entries</h3>
<div class="main-container">
  <%= will_paginate %> 
  <%= render @entries %> 
  <%= will_paginate %> 
</div>

app/views/entries/new.html.erb
<h1 class="page-title">New Entry</h1>
<div class="main-container">
  <%= render 'entry_form' %>
</div>

app/views/entries/show.html.erb
<div class="main-container">
  <%= image_tag @entry.display_image, class: "entry-show-image" if @entry.image.attached? %> 
  <h1 class="entry-show-title"> <%= @entry.title %> </h1>
  <p class="entry-show-date"> <%= @entry.created_at.strftime("%d-%m-%Y") %> </p>
  <p class="entry-show-abstract"> <%= @entry.abstract %> </p>
  <%= render @entry.sections %> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GarrettForsythBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div class="flash-container">
    <% flash.each do |message_type, message| %> 
      <%= content_tag(:div, message, class: "flash flash-#{message_type}") %> 
    <% end %> 
  </div>

  <%= render "shared/header" %> 

  <body>
    <%= yield %>
  </body>
</html>

app/views/sections/_section.html.erb
<%= image_tag  section.display_image, class: "section-image" if section.image.attached? %> 
<p class="section-content">
  <%= raw section.content %> 
</p>
<%= render section.code_snippet if section.code_snippet %> 

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>        
<div id="error_explanation">        
  <div>        
  The form contains <%= pluralize(object.errors.count, "error") %>.        
    </div>        
  <ul>        
    <% object.errors.full_messages.each do |msg| %>        
    <li><%= msg %></li>        
    <% end %>        
  </ul>        
</div>        
<% end %> 

app/views/shared/_header.html.erb
<div class="container social">
  <table>
    <tr>
      <th>Home</th>
      <th>All Entries</th>
      <th>Email</th>
      <th>Github</th>
      <th>Twitter</th>
    </tr>
    <tr>
      <td>
        <%= link_to image_tag("home.svg", id: "home-icon", class: "header-icon"), root_path  %> 
      </td>
      <td>
        <%= link_to image_tag("blogs.svg", id: "blogs-icon", class: "header-icon"), entries_path %> 
      </td>
      <td>
        <a href="mailto:gtforsyth91@gmail.com">
         <%= image_tag "email.svg", id: "social-email-icon", class: "header-icon" %>
        </a>
      </td>
      <td>
        <a href="https://github.com/GarrettForsyth">
         <%= image_tag "github.svg", id: "social-github-icon", class: 'header-icon'%>
        </a>
      </td>
      <td>
       <a href="https://twitter.com/forsyth_garrett">
         <%= image_tag "twitter.svg", id: "social-twitter-icon", class: 'header-icon'%>
       </a>
      </td>
    </tr>
  </table>
  <ul class="hidden">
    <li>
      <a href="mailto:gtforsyth91@gmail.com">
        gtforsyth91@gmail.com
      </a>
    </li>
    <li>
      <a href="https://github.com/GarrettForsyth">
        /GarrettForsyth
      </a>
    </li>
    <li>
      <a href="https://twitter.com/forsyth_garrett">
        @forsyth_garrett
      </a>
    </li>
  </ul>
</div>

app/views/static_pages/admin.html.erb
<h1 class="page-title">Admin Page</h1>
<div class="main-container">
  <%= will_paginate @entries %> 
  <%= render @entries %> 
  <%= will_paginate @entries %> 
</div>

app/views/static_pages/home.html.erb
<div class="container">
  <div class="profile">
    <%= image_tag "blog_profile_image.jpg", id: "profile-image", size: "267x200" %> 
    <h1>Garrett Forsyth</h1>
  </div>
</div>

<div class="main-container">
  <ol class="entries-list">
    <%= render @recent_entries %> 
  </ol>
</div>